"""Type stubs for the BEMtzmann native extension."""

from __future__ import annotations

from enum import Enum

import numpy as np
from numpy.typing import NDArray

_F64Array1 = NDArray[np.float64]
_F64Array2 = NDArray[np.float64]
_U32Array2 = NDArray[np.uint32]

class ChargeSide(Enum):
    Interior = ...
    Exterior = ...

class Dielectric:
    def __init__(self, eps_in: float, eps_out: float, kappa: float = 0.0) -> None: ...
    @property
    def eps_in(self) -> float: ...
    @property
    def eps_out(self) -> float: ...
    @property
    def kappa(self) -> float: ...

class Surface:
    @staticmethod
    def icosphere(radius: float, subdivisions: int) -> Surface: ...
    @staticmethod
    def from_mesh(vertices: _F64Array2, faces: _U32Array2) -> Surface: ...
    @staticmethod
    def from_msms(vert_path: str, face_path: str) -> Surface: ...
    @property
    def num_vertices(self) -> int: ...
    @property
    def num_faces(self) -> int: ...
    def classify_charges(self, positions: _F64Array2) -> ChargeSide: ...

class BemSolution:
    @staticmethod
    def solve(
        surface: Surface,
        media: Dielectric,
        side: ChargeSide,
        positions: _F64Array2,
        charges: _F64Array1,
    ) -> BemSolution: ...
    def reaction_field_at(self, point: tuple[float, float, float]) -> float: ...
    def reaction_field_at_many(self, points: _F64Array2) -> _F64Array1: ...
    def interaction_energy(
        self,
        positions: _F64Array2,
        charges: _F64Array1,
        i: int,
        j: int,
    ) -> float: ...

class LinearResponse:
    @staticmethod
    def precompute(
        surface: Surface,
        media: Dielectric,
        side: ChargeSide,
        sites: _F64Array2,
    ) -> LinearResponse: ...
    @property
    def num_sites(self) -> int: ...
    def solvation_energy(self, charges: _F64Array1) -> float: ...
    def reaction_field_at_sites(self, charges: _F64Array1) -> _F64Array1: ...
    def reaction_field_at(
        self,
        charges: _F64Array1,
        point: tuple[float, float, float],
    ) -> float: ...
    def reaction_field_at_many(
        self,
        charges: _F64Array1,
        points: _F64Array2,
    ) -> _F64Array1: ...

def read_pqr(path: str) -> tuple[_F64Array2, _F64Array1]: ...
def read_xyz(path: str) -> tuple[_F64Array2, _F64Array1]: ...
def to_kJ_per_mol(energy: float) -> float: ...
def to_kt(energy: float, temperature_k: float) -> float: ...
